### PR TITLE
Fix mypy CI job

### PR DESCRIPTION
**Pull request by AlexWaygood**
The 3.13 job seems to have started failing, not sure why: https://github.com/PyCQA/flake8-pyi/actions/runs/10469760712/job/28993477108?pr=497

### CODE REVIEW

**Comment by AlexWaygood** [comment]
I guess we could also just use a Python 3.12 installation for both mypy jobs and run with `--target-version 3.13`; no strong opinion on which is better there

**Comment by srittau** [comment]
I like using `--target-version`. The version mypy runs on shouldn't be important, and using a relatively new, but stable Python version seems to be the safest to me.

**Comment by AlexWaygood** [comment]
oh, we need to run the mypy-3.8 job using Python 3.8, or the optional dependency `ast_decompiler` isn't installed.

**Review by srittau — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> > oh, we need to run the mypy-3.8 job using Python 3.8, or the conditional dependency `ast_decompiler` isn't installed, which is necessary for typechecking to succeed on Python 3.8
> 
> Could you add a comment about that to the yml file?

done!

**Review by srittau — APPROVED** [review]

**Pull request merged**
