### PR TITLE
Add Y037 code to check for possible usage of PEP 604 new syntax

### LINKED ISSUE #45: Suggest using PEP 604-style union types
Humble suggestion: add new code to suggest a replacement of `Union[...]` types with the `|` chain, e.g. `Y093 Use PEP 604 union types`. A simple implementation start could be e.g.
```py
class PyVisitor(ast.NodeVisitor):
    ...
     def visit_FunctionDef(self, node):
        if node.returns.value is not None and node.returns.value.id in ("Optional", "Union"):
            self.error(node.returns, Y093)
        ...

    def visit_arguments(self, node):
        if arg.annotation.value.id in ("Optional", "Union"):
            self.error(arg, Y093)
        ...
```

### PR DESCRIPTION
**Pull request by AlexWaygood**
Closes #45 (a continuation of @hoefling's PR #184, which I accidentally closed).

### CODE REVIEW

**Comment by AlexWaygood** [comment]
@hoefling are you happy with the tweaks I made to the error messages in cb93b35?

**Comment by JelleZijlstra** [comment]
Thanks, I'd prefer to turn the new code off in typeshed for now; we can just rely on check_new_syntax.py and code review in the meantime.

**Comment by AlexWaygood** [comment]
> Thanks, I'd prefer to turn the new code off in typeshed for now; we can just rely on check_new_syntax.py and code review in the meantime.

https://github.com/python/typeshed/pull/7600

**Comment by AlexWaygood** [comment]
Aand we have a green CI!

**Review by Akuli — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Thanks for the PR @hoefling!

**Pull request merged**
