### PR TITLE
Expand Y015 to cover assignments to negative numbers

### PR DESCRIPTION
**Pull request by AlexWaygood**
Refs #286. Involves a little bit of refactoring as we were running up against the McCabe complexity limit for `visit_Assign`.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
The test failures in 3.7/3.8 should be fixed by https://github.com/JelleZijlstra/ast_decompiler/pull/48 :)

**Comment by hauntsaninja** [comment]
Lol, I didn't realise we were still using decompiler. We should consider switching to ast.unparse and dropping older Pythons. (For completeness, there's also https://github.com/simonpercivall/astunparse/pulls which last time I checked was in some ways better than decompiler ... but also my PRs fixing some issues with it haven't been merged in two years)

**Comment by AlexWaygood** [comment]
> We should consider switching to ast.unparse and dropping older Pythons.

We only use it on Python 3.7 and 3.8 -- we use `ast.unparse` on 3.9+. I don't feel the need to drop support for Python 3.8 just yet, it's not too much of a pain :)

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
> Lol, I didn't realise we were still using decompiler. We should consider switching to ast.unparse and dropping older Pythons. (For completeness, there's also https://github.com/simonpercivall/astunparse/pulls which last time I checked was in some ways better than decompiler ... but also my PRs fixing some issues with it haven't been merged in two years. Edit: never mind, looks like Jelle's fixed a bunch of things in ast_decompiler recently :-) )

At least you know who to talk to to get `ast_decompiler` bugs fixed :)

**Pull request merged**
