### PR TITLE
Use ast_decompiler from pypi when ast.unparse isn't available

### PR DESCRIPTION
**Pull request by Akuli**
I generally don't like adding dependencies to projects, but I think it's justified in this case:
- The dependency does something nontrivial. It is about 1100 lines of code.
- The dependency is used only with older Python versions.
- We trust the author of the dependency.
- We can do better error messages with the dependency.
- Code is cleaner with the dependency.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
This is _great_.

**Comment by AlexWaygood** [comment]
Should we maybe add something to the changelog about dropping the `attrs` dependency and adding this one?

**Review by JelleZijlstra — APPROVED** [review]
Looks good!

There are several other options, e.g. those listed in https://astunparse.readthedocs.io/en/latest/. I haven't maintained ast-decompiler too much but I think it should be fine for our use cases.

**Comment by Akuli** [comment]
We can switch to a different library later if needed, but we shouldn't need a well-maintained library, because the library is used only on the ast of older Python versions.

**Pull request merged**
