### PR TITLE
Make Y060 more aggressive

### PR DESCRIPTION
**Pull request by AlexWaygood**
This implements Jelle's suggestion from https://github.com/PyCQA/flake8-pyi/pull/431#discussion_r1373505939

@JelleZijlstra, what do you think? Would the required changes to typeshed be a net win for readability, or a net loss?

### CODE REVIEW

**Review by srittau — APPROVED** [review]
LGTM. I don't see a problem with the new warnings. (But don't feel particularly strongly about it.)

**Comment by AlexWaygood** [comment]
Should we also flag classes like https://github.com/python/typeshed/blob/3a56e0034c98cadf935ab1f57ca852702cbcfed2/stdlib/ipaddress.pyi#L73? I have a patch locally that does so

**Comment by srittau** [comment]
Sure, would make sense to me.

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
Could we add tests for the case where Generic is used to reorder type variables?

**Comment by AlexWaygood** [comment]
> Could we add tests for the case where Generic is used to reorder type variables?

Good idea!

**Comment by AlexWaygood** [comment]
https://github.com/python/typeshed/pull/10981 shows the changes that would be needed in typeshed if this was merged

**Review by srittau — APPROVED** [review]

**Review by hauntsaninja — APPROVED** [review]
Looks good! I wouldn't mind a `class GoodGeneric7(Mapping[_S, _T], Generic[_T, _S]): ...` as well

**Pull request merged**
