### PR TITLE
Extend Y034 to cover in-place BinOp dunder methods

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by AlexWaygood** [comment]
All the typeshed hits are in Python 2; I can prepare a backport PR for typeshed if we think this change is a good idea.

**Review by JelleZijlstra — APPROVED** [review]
Makes sense

**Comment by AlexWaygood** [comment]
Backport typeshed PR here: https://github.com/python/typeshed/pull/7166

**Comment by AlexWaygood** [comment]
... And a second typeshed PR: https://github.com/python/typeshed/pull/7167

**Pull request merged**
